export interface Company {
  id: string
  name: string
  tagline: string
  desc: string
  url: string
  category: string
  stats: string
  color: string
  icon: string
  iconImage?: string
  cardSubtitle?: string
  cardMeta?: string
  internal?: boolean
  founded?: string
  headquarters?: string
  highlights?: string[]
  offerings?: string[]
  audience?: string[]
  sourceUrls?: string[]
  longDesc?: string
  keyFacts?: string[]
  certifications?: string[]
  businessModel?: string[]
  geographicReach?: string
  notableClients?: string[]
  socialProof?: string
  contactInfo?: string
  parentGroup?: string
}

const COMMON_COMPANY_ADDRESS = 'Office no. 201-202, Hirubai Residency, Virar (West), Maharashtra, India.'

export const COMPANIES: Company[] = [
  {
    id: 'ptcgram',
    name: 'PTCGRAM Pvt. Ltd.',
    tagline: 'Leading Chemical Distributor',
    desc: 'Leading distributors and manufacturers of specialty chemicals, solvents, acids and industrial solutions since 2006, serving clients across India and globally.',
    longDesc:
      'PTCGRAM PVT LTD is a TrustSEAL verified manufacturer, wholesaler, supplier, and exporter of specialty chemicals based in Virar East, Maharashtra. With over 15 years of industry expertise, the company has built a diverse product portfolio spanning industrial chemicals, solvents, acids, ethanol, vitamins, fragrances, essential oils, and household cleaning concentrates. Their commitment to treating suppliers as partners and valuing long-term customer relationships is central to their philosophy, serving clients ranging from small enterprises to large corporations across multiple industries.',
    url: 'https://ptcgram.com',
    category: 'Chemicals',
    stats: '500+ Products',
    cardSubtitle: 'Specialty Chemicals & Industrial Solutions',
    cardMeta: '500+ Products • Since 2009',
    color: '#C8912B',
    icon: 'CH',
    iconImage: '/Images/CH-Favicon.png',
    founded: '2006',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'TrustSEAL verified manufacturer and exporter on IndiaMART',
      'Over 50 chemicals marketed across wide industrial applications',
      'Diversified into essential oils and fragrances over last decade',
      'Active Research & Development investments for product portfolio growth',
      'Associated with a Technology Excellence Group for cross-pollinating best practices',
    ],
    offerings: [
      'Solvents (Methanol, Iso Butyl Alcohol, Iso Butanol)',
      'Acids and industrial chemicals',
      'Ethanol and ethyl-based solutions',
      'Household cleaning concentrates (Phenyl, Floor Cleaner, Pine Oil)',
      'Fragrance and essential oils (Lemon Grass, Lavender, Diffuser Reed Oils)',
      'Vitamins and specialty wellness inputs',
      'PPE Kits and sanitization products',
      'Plastic bottles and packaging containers',
      'Carbopol Powder (cosmetic and pharma grade)',
      'Polyvinyl Alcohol (PVA) - industrial grade',
    ],
    audience: [
      'Manufacturing and processing industries',
      'FMCG and consumer goods companies',
      'Pharmaceutical and cosmetics manufacturers',
      'Trading businesses and wholesalers',
      'Export-oriented industrial clients',
    ],
    businessModel: ['Manufacturer', 'Wholesaler', 'Trader', 'Exporter'],
    geographicReach: 'Pan-India distribution; exporter to international markets',
    keyFacts: [
      'GST: 27AALCP9913F1Z2',
      '91% response rate on IndiaMART',
      'Serves small enterprises to large corporations',
      'Products include 99.9% germ-killing floor cleaners and phenyl concentrates',
      'Methanol: 99% purity, 12-month shelf life, industrial grade',
    ],
    sourceUrls: ['https://ptcgram.com', 'https://ptcgram.com/about/', 'https://www.indiamart.com/ptc-mumbai/about-us.html'],
  },
  {
    id: 'ptc-logistics',
    name: 'PTC Logistics',
    tagline: 'Pan India Transport and Global Logistics',
    desc: 'Leading integrated logistics and mobility solutions provider with over a decade of experience, catering to 400+ clients including Godrej and pharmaceutical sector majors.',
    longDesc:
      "PTC Logistics is a comprehensive freight and logistics company offering road, air, and sea transportation services across India and internationally. The company operates on a ton-basis pricing model and is focused on delivering affordable, time-sensitive logistics to industrial, chemical, and distribution businesses. With a strong foothold in the chemical logistics segment - a natural extension of the PTC Group's chemicals business - PTC Logistics serves as the supply chain backbone for group companies and external clients alike.",
    url: 'https://ptclogistics.in',
    category: 'Logistics',
    stats: '400+ Clients',
    cardSubtitle: 'Transport, Mobility & Supply Chain Solutions',
    cardMeta: '400+ Clients Served',
    color: '#2B6CB0',
    icon: 'LG',
    iconImage: '/Images/LG-Logo.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Over a decade of integrated logistics experience',
      'Serving 400+ clients on a regular basis',
      'Prestigious clients include Godrej and pharmaceutical sector leaders',
      'Ton-based pricing model for competitive freight rates',
      'Multi-modal freight: road, air, and sea in one solution',
    ],
    offerings: [
      'Road freight (domestic Pan-India)',
      'Air freight services',
      'Sea freight and container movement',
      'Import and export logistics support',
      'Chemical logistics (specialized for hazardous and industrial cargo)',
      'Time-sensitive dispatch and last-mile delivery',
    ],
    audience: [
      'Industrial clients and manufacturers',
      'Chemical distribution businesses',
      'Pharmaceutical companies',
      'Exporters and importers',
      'FMCG distribution networks',
    ],
    businessModel: ['B2B freight services', 'Contractual logistics partnerships', 'Ton-based freight pricing'],
    geographicReach: 'Pan-India; import-export international freight support',
    notableClients: ['Godrej', 'Pharma sector leaders', 'Distilleries'],
    keyFacts: [
      "One of India's leading integrated logistics providers",
      'Specializes in affordable freight rates for industrial clients',
      'Handles both domestic and cross-border freight',
      'Operates across all major Indian transportation corridors',
    ],
    sourceUrls: ['https://ptclogistics.in', 'https://ptclogistics.in/index.php/air-freight/'],
  },
  {
    id: 'ilika',
    name: 'Ilika',
    tagline: 'Skincare, Haircare and Grooming Tools',
    desc: 'Premium skincare and haircare brand founded in 2018, offering 100% genuine, cruelty-free and vegan formulations focused on healing-first cosmetics for Indian skin.',
    longDesc:
      'Ilika is a consumer beauty brand under PTCGRAM PVT LTD, led by Managing Director Mr. Vipul Singh. Founded in 2018 in Mumbai, Ilika is on a mission to redefine skincare and cosmetics through healing-first formulations that celebrate natural beauty. The brand emphasizes non-invasive techniques, with products tailored specifically for Indian skin types. All products are 100% genuine, authentic, organic, cruelty-free, vegan, and free from harsh chemicals. Ilika ships pan-India and is available on Amazon, JioMart, Meesho, and its own website.',
    url: 'https://ilika.in',
    category: 'Personal Care',
    stats: 'Since 2018',
    cardSubtitle: 'Skincare, Haircare & Beauty Devices',
    cardMeta: 'Trusted by thousands of customers',
    color: '#00A3C4',
    icon: 'IL',
    iconImage: '/Images/Favicon.webp',
    founded: '2018',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTCGRAM PVT LTD',
    highlights: [
      'Founded in 2018 in Mumbai with a healing-first skincare philosophy',
      'Products formulated specifically for Indian skin types',
      'Cruelty-free, vegan, and free from harsh chemicals',
      '7,700+ Instagram followers and active pan-India D2C presence',
      'Available on Amazon, JioMart, and Meesho in addition to own website',
    ],
    offerings: [
      'Ceramide Gel Moisturizer (barrier repair, anti-aging)',
      'Collagen Serum with Hyaluronic Acid and Niacinamide',
      'Face wash and cleansers',
      'Suncare and skin protection products',
      'Hair care: conditioners and nourishing toners',
      'Grooming tools and facial care appliances',
      'Lip balms (organic, vegan, plastic-free)',
      'Baby care products',
    ],
    audience: [
      'Direct-to-consumer beauty buyers',
      'Skincare-conscious Indian consumers',
      'Users seeking vegan and cruelty-free products',
      'Parents looking for gentle baby care',
    ],
    certifications: ['Cruelty-Free', 'Vegan', 'No harsh chemicals'],
    businessModel: ['D2C via own website', 'E-commerce marketplaces (Amazon, JioMart, Meesho)', 'Pan-India shipping'],
    geographicReach: 'Pan-India shipping; D2C e-commerce',
    keyFacts: [
      'Manufacturing address: Unit No. 5, Ground Floor, Pragati Compound, Vasai-Bhiwandi Road, Thane-401208',
      'Manufacturer: PTCGRAM PVT LTD',
      'Available on Amazon India with verified reviews',
      'Ilika Ceramide Gel Moisturizer enriched with Hyaluronic Acid and Vitamin E',
    ],
    socialProof: '7,763 Instagram followers (@ilikamumbai), 338+ posts, since 2021',
    sourceUrls: ['https://ilika.in', 'https://www.ilika.in/about%20us/', 'https://www.ilika.in/hair-care/', 'https://about.me/ilika'],
  },
  {
    id: 'the-futurex',
    name: 'The FutureX',
    tagline: 'Smart Wearables Brand',
    desc: "Indian technology brand offering a full range of smart wearables - smart bands, smart rings, and smart watches - designed for connected, fitness-focused lifestyles.",
    longDesc:
      "TheFutureX (thefuturex.in) is a consumer technology brand positioned squarely in the fast-growing Indian wearables market - a market that has made India the world's largest smartwatch market. The brand offers a catalog spanning smart bands, smart rings, smart watches, and smart home lifestyle gadgets. TheFutureX targets fitness-conscious consumers and digital lifestyle users who want connected health monitoring without the premium price points of global giants, combining daily wellness tracking with modern design.",
    url: 'https://thefuturex.in/',
    category: 'Technology',
    stats: 'Smart Wearables',
    cardSubtitle: 'Smart Wearables & Consumer Technology',
    cardMeta: 'Smart Rings • Smart Bands • Smart Watches',
    color: '#553C9A',
    icon: 'TX',
    iconImage: '/Images/TX-Favicon.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    highlights: [
      'Full smart wearables catalog: bands, rings, and watches',
      "Positioned in India's high-growth wearables segment",
      'Health and fitness monitoring as core product utility',
      'Affordable smart wearables for connected Indian consumers',
      'Expanding into smart home lifestyle gadgets',
    ],
    offerings: [
      'Smart bands (activity and fitness tracking)',
      'Smart rings (health monitoring, sleep tracking)',
      'Smart watches (connected lifestyle, notifications)',
      'Smart fans and home lifestyle gadgets',
      '24x7 health monitoring wearables',
    ],
    audience: [
      'Fitness-focused users',
      'Health-tracking enthusiasts',
      'Digital lifestyle consumers',
      'Tech-savvy Indian buyers seeking affordable wearables',
    ],
    businessModel: ['D2C e-commerce via own website', 'Consumer electronics retail'],
    geographicReach: 'India-focused; pan-India e-commerce delivery',
    keyFacts: [
      "Operates in India's world-leading smartwatch market",
      'Covers all major wearable form factors (band, ring, watch)',
      'Targets second/third-generation wearable upgrade buyers',
      'Smart rings offer sleep tracking and health monitoring without a display',
    ],
    sourceUrls: ['https://thefuturex.in', 'https://thefuturex.in/shop/'],
  },
  {
    id: 'kedos',
    name: 'Kedos',
    tagline: 'Baby Care Products',
    desc: 'Consumer-focused baby care brand under the PTC Group, offering everyday hygiene, comfort, and skincare products for infants and families.',
    longDesc:
      "Kedos is a baby care brand developed under the PTC Group umbrella, bringing together the group's chemical manufacturing and consumer product expertise to create safe, everyday-use products for infants and families. The brand focuses on hygiene essentials, baby skincare, and daily care consumables, designed with a family-first approach. Given the PTC Group's roots in manufacturing and chemicals, Kedos products leverage in-house ingredient sourcing and formulation know-how to deliver quality baby care at accessible price points.",
    url: 'https://kedos.in',
    category: 'Baby Care',
    stats: 'Everyday Care',
    color: '#38A169',
    icon: 'BC',
    iconImage: '/Images/BC-Favicon.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      "Baby care brand leveraging PTC Group's formulation expertise",
      'Designed for everyday infant hygiene and comfort',
      'Family-first product philosophy',
      'In-house ingredient sourcing advantage from PTCGRAM chemicals division',
    ],
    offerings: [
      'Baby hygiene products (wash, shampoo, lotion)',
      'Baby skincare essentials',
      'Daily care consumables (wipes, powder)',
      'Infant comfort and grooming products',
    ],
    audience: [
      'Parents and primary caregivers',
      'Infant care households',
      'Retail and D2C buyers',
    ],
    businessModel: ['D2C e-commerce', 'Retail distribution'],
    geographicReach: 'India-wide',
    keyFacts: [
      "Backed by PTC Group's chemical and manufacturing infrastructure",
      'Positioned as an affordable, quality baby care option',
      'Products formulated for gentle infant skin',
    ],
    sourceUrls: ['https://kedos.in'],
  },
  {
    id: 'devang-organics',
    name: 'Devang Organics',
    tagline: 'Organic Ingredient Products',
    desc: 'Organic ingredient supplier and product brand serving food, wellness, and clean-label formulation markets for both consumer and industrial clients across India.',
    longDesc:
      "Devang Organics specializes in organic ingredients and herbal-oriented products for use across food processing, wellness formulations, and clean-label consumer applications. The brand bridges the gap between raw organic ingredient supply and finished product delivery, catering to ingredient buyers, wellness brands, and manufacturers looking for certified natural inputs. As part of the PTC Group, Devang Organics benefits from established supply chains and quality controls within the group's chemicals and manufacturing operations.",
    url: 'https://www.devangorganics.com/',
    category: 'Organics',
    stats: 'Ingredient Focus',
    color: '#68A35A',
    icon: 'OR',
    iconImage: '/Images/OR-Favicon.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Organic and herbal ingredient sourcing for multiple industries',
      'Clean-label formulation focus for food and wellness applications',
      'Bridges ingredient supply and finished product development',
      'Serves both B2B ingredient buyers and B2C wellness consumers',
    ],
    offerings: [
      'Organic food ingredients',
      'Herbal and botanical extracts',
      'Natural wellness inputs and nutraceutical ingredients',
      'Clean-label formulation components',
      'Essential organic inputs for personal care manufacturing',
    ],
    audience: [
      'Food manufacturers and processors',
      'Wellness and nutraceutical brands',
      'Organic product formulators',
      'Ingredient procurement teams',
    ],
    businessModel: ['B2B ingredient supply', 'Consumer organic products'],
    geographicReach: 'India; potential for export-oriented organic ingredient supply',
    keyFacts: [
      'Focused on clean-label and organic certification alignment',
      'Leverages PTC Group sourcing and quality networks',
      'Supports both industrial and consumer-facing organic applications',
    ],
    sourceUrls: ['https://www.devangorganics.com/'],
  },
  {
    id: 'the-himalayan-brewery',
    name: 'The Himalayan Brewery',
    tagline: 'Crafted in the Mountains',
    desc: 'Artisan beverage brand inspired by Himalayan purity, crafting premium beverages from pristine glacial waters for modern lifestyle and hospitality markets.',
    longDesc:
      "The Himalayan Brewery (thehimalayanbrewery.com) is a lifestyle beverage brand positioned around the purity and character of Himalayan origins. Inspired by the concept of brewing with pristine glacial waters and the spirit of the world's highest mountains, the brand targets modern beverage consumers who value craft, provenance, and premium quality. The brand is oriented toward both retail consumers and hospitality channels, aiming to build a strong lifestyle identity in the growing craft and premium beverage segment in India.",
    url: 'https://thehimalayanbrewery.com',
    category: 'Beverages',
    stats: 'Artisan Craft',
    color: '#744210',
    icon: 'BV',
    iconImage: '/Images/BV-Favicon.webp',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Premium craft beverage brand with Himalayan identity',
      'Positioned around pristine glacial water sourcing and mountain purity',
      'Targeted at lifestyle and hospitality-facing beverage channels',
      'Brand story built on extraordinary character and artisan craft values',
    ],
    offerings: [
      'Craft beverages (mountain-inspired)',
      'Hospitality-aligned beverage line',
      'Lifestyle and premium retail beverage products',
    ],
    audience: [
      'Retail consumers seeking premium craft beverages',
      'Hotels, restaurants, and hospitality venues',
      'Lifestyle-conscious beverage buyers',
    ],
    businessModel: ['Retail distribution', 'Hospitality and HoReCa channel', 'D2C brand positioning'],
    geographicReach: 'India; premium retail and hospitality markets',
    keyFacts: [
      'Brand narrative centered on "pristine glacial waters meet ancient grain"',
      'Designed for the modern premium beverage consumer',
      'Hospitality and lifestyle channel focused go-to-market',
    ],
    sourceUrls: ['https://thehimalayanbrewery.com'],
  },
  {
    id: 'the-himalayan-store',
    name: 'The Himalayan Store',
    tagline: 'Mountain Essentials',
    desc: 'Curated e-commerce platform offering authentic Himalayan goods - foods, wellness products, and lifestyle items - sourced from the mountain regions of India.',
    longDesc:
      "The Himalayan Store (thehimalayanstore.shop) is a D2C retail platform curating authentic Himalayan-origin products spanning food, wellness, and lifestyle categories. The store targets consumers who value provenance, authenticity, and the wellness associations of Himalayan sourcing - from herbal foods to natural lifestyle essentials. It serves as the retail face of the PTC Group's Himalayan brand ecosystem, offering a curated shopping experience for D2C buyers, gifting customers, and wellness consumers seeking mountain-sourced goods.",
    url: 'https://thehimalayanstore.shop',
    category: 'Retail',
    stats: 'Curated Collection',
    color: '#B7791F',
    icon: 'RT',
    iconImage: '/Images/RT-Logo.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Curated D2C platform for authentic Himalayan goods',
      'Covers food, wellness, and lifestyle product categories',
      'Gifting-friendly product assortment with premium positioning',
      'Leverages Himalayan provenance as a strong brand differentiator',
    ],
    offerings: [
      'Himalayan foods (natural, traditional, region-specific)',
      'Wellness products (herbal, natural)',
      'Lifestyle and gifting items',
      'Himalayan-inspired personal care and home goods',
    ],
    audience: [
      'D2C online shoppers',
      'Gift buyers seeking premium and authentic products',
      'Wellness-focused consumers',
      'Himalayan culture and heritage enthusiasts',
    ],
    businessModel: ['D2C e-commerce platform', 'Curated marketplace for Himalayan goods'],
    geographicReach: 'Pan-India online retail; gifting nationwide',
    keyFacts: [
      'Operates as an e-commerce-first retail destination',
      'Part of The Himalayan brand family within PTC Group',
      'Positioned at the intersection of wellness and Himalayan heritage',
    ],
    sourceUrls: ['https://thehimalayanstore.shop'],
  },
  {
    id: 'zaura-care',
    name: 'Zaura Care',
    tagline: 'Medical Product Range',
    desc: 'Healthcare product brand offering medical-grade consumables, rapid diagnostic test kits, and clinical essentials for hospitals, clinics, and medical distribution partners.',
    longDesc:
      "Zaura Care (zauracare.com) is a medical and healthcare product brand focused on dependable quality, safety, and everyday clinical needs. The brand covers the healthcare consumables and diagnostics segment, with rapid test kits serving as a core offering for clinics and healthcare procurement teams. Zaura Care is designed to meet the standards required by professional healthcare buyers while offering products accessible enough for pharmacy and clinic-level deployment. As part of the PTC Group, it benefits from the group's established supply chain and quality assurance capabilities.",
    url: 'https://www.zauracare.com/',
    category: 'Medical',
    stats: 'Healthcare First',
    color: '#D53F8C',
    icon: 'MD',
    iconImage: '/Images/MD-Favicon.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Medical-grade product range with reliability at the core',
      'Rapid diagnostic test kits for point-of-care clinical use',
      'Healthcare consumables for clinics, hospitals, and pharmacies',
      "Backed by PTC Group's quality and supply chain infrastructure",
    ],
    offerings: [
      'Rapid diagnostic test kits (dengue, malaria, typhoid, and more)',
      'Healthcare consumables and clinical essentials',
      'General medical disposables',
      'Point-of-care testing products',
    ],
    audience: [
      'Hospitals and clinics',
      'Healthcare procurement professionals',
      'Medical distributors and wholesalers',
      'Pharmacies and diagnostic centres',
    ],
    certifications: ['Medical-grade quality standards'],
    businessModel: ['B2B medical distribution', 'Healthcare supply partnerships'],
    geographicReach: 'India-wide healthcare distribution',
    keyFacts: [
      'Rapid test kits suitable for qualitative detection of common infectious diseases',
      'Products designed for ease of use in clinical settings',
      'Focused on safety-critical healthcare applications',
    ],
    sourceUrls: ['https://www.zauracare.com/'],
  },
  {
    id: 'ss-packaging',
    name: 'SS Packaging',
    tagline: 'Bottle and Container Packaging',
    desc: 'Premium packaging solutions provider specializing in bottles, containers, jars, and cosmetic packaging sets for beauty, personal care, and retail brands across India.',
    longDesc:
      "SS Packaging (sspackaging.co.in) is a packaging solutions company specializing in bottles, containers, jars, and cosmetic-grade packaging for personal care, beauty, and retail product brands. The company sources from quality suppliers including glass, bamboo, and sustainable materials, and offers fast, reliable delivery across India. SS Packaging serves as a natural extension of the PTC Group's ecosystem - supplying the packaging infrastructure that complementary group brands like Ilika and Kedos can leverage for their own products, while also serving external cosmetic and personal care clients.",
    url: 'https://www.sspackaging.co.in/',
    category: 'Packaging',
    stats: 'Packaging Solutions',
    cardSubtitle: 'Bottles, Containers & Packaging Solutions',
    cardMeta: 'Cosmetic • Pharma • FMCG Packaging',
    color: '#4A5568',
    icon: 'PK',
    iconImage: '/Images/PK-Favicon.png',
    headquarters: COMMON_COMPANY_ADDRESS,
    contactInfo: COMMON_COMPANY_ADDRESS,
    parentGroup: 'PTC Group',
    highlights: [
      'Specialized in cosmetic and personal care packaging formats',
      'Premium packaging sourced from top suppliers including glass and bamboo',
      'Sustainable packaging options alongside traditional plastic formats',
      'Fast and reliable pan-India delivery for packaging clients',
      'Serves as in-house packaging partner for PTC Group consumer brands',
    ],
    offerings: [
      'Plastic and glass bottles (various sizes)',
      'Jars and containers (cosmetic and general)',
      'Airless pump bottles for serums and lotions',
      'Cosmetic packaging sets (complete solutions)',
      'Bamboo and sustainable packaging alternatives',
      'Custom packaging options for brands',
    ],
    audience: [
      'Cosmetic and personal care brands',
      'Beauty and skincare manufacturers',
      'FMCG packaging procurement teams',
      'Retail product brands requiring custom packaging',
    ],
    certifications: ['Premium supplier sourcing standards'],
    businessModel: ['B2B packaging supply', 'Wholesale packaging distribution', 'Custom packaging solutions'],
    geographicReach: 'Pan-India delivery',
    keyFacts: [
      'Sources from finest suppliers including bamboo, glass, and eco materials',
      'Serves both internal PTC Group brands and external clients',
      'Complete packaging solution from design format to delivery',
    ],
    sourceUrls: ['https://www.sspackaging.co.in/'],
  },
]

export const CATEGORIES = ['All', ...Array.from(new Set(COMPANIES.map((c) => c.category)))]

export const GROUP_STATS = [
  { value: '15+', label: 'Years in Business' },
  { value: '10+', label: 'Businesses & Brands' },
  { value: '1000+', label: 'Clients Served' },
  { value: '50+', label: 'Industry Partners' },
]
